// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuwoFGyIiuV_ix0avO__0OKJ861RzdwAQ',
    appId: '1:223459708235:web:eb16b3b27ab7d491262cce',
    messagingSenderId: '223459708235',
    projectId: 'insta-teacher',
    authDomain: 'insta-teacher.firebaseapp.com',
    storageBucket: 'insta-teacher.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAutaLiIY044oxefrBNitXhRSc6Ggk_geY',
    appId: '1:223459708235:android:2ad4e0c54270907e262cce',
    messagingSenderId: '223459708235',
    projectId: 'insta-teacher',
    storageBucket: 'insta-teacher.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0Yu2blwLNvqoWxolr8yKRqBMh6QVHKX8',
    appId: '1:223459708235:ios:ebd7e442398bce80262cce',
    messagingSenderId: '223459708235',
    projectId: 'insta-teacher',
    storageBucket: 'insta-teacher.appspot.com',
    iosBundleId: 'com.example.instaTeacher',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0Yu2blwLNvqoWxolr8yKRqBMh6QVHKX8',
    appId: '1:223459708235:ios:64782bec277ab0ac262cce',
    messagingSenderId: '223459708235',
    projectId: 'insta-teacher',
    storageBucket: 'insta-teacher.appspot.com',
    iosBundleId: 'com.example.instaTeacher.RunnerTests',
  );
}
